// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_appsync_graphqlEndpoint": "https://cjcpc2p6trdq3loyhmb66bprty.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-au3rz2723bgudg7tfvtoiyh6si",
};

export default awsmobile;